### ISSUE TITLE
[Feature Request] Add setting to only snap template origin points to grid intersections

### ISSUE THREAD

**Issue by nschoenwald** [TesserWract/snappy-templates#1]
I would love if this module could force origin points to only snap to grid intersections (as opposed to the center of grid squares).

**Comment by TesserWract** [comment]
Added in release [1.1.0](https://github.com/TesserWract/snappy-templates/releases/tag/1.1.0). Be sure to update the module in Foundry.

**Comment by nschoenwald** [comment]
Awesome, thank you so much!

**Comment by nschoenwald** [comment]
@TesserWract Unfortunately the setting does not seem to work or at least not as I expected.
I set it to "corner only" but the templates still also snap to the center.
You can see in this video recording: https://youtu.be/28EfY9_MIwM

**Comment by TesserWract** [comment]
I see what the problem is, the origin snapping logic only applied to newly created templates and didn't touch them after that. In [1.1.1](https://github.com/TesserWract/snappy-templates/releases/tag/1.1.1) I have fixed this issue so that they will always use the same snap logic whether they are new or existing templates.

**Comment by nschoenwald** [comment]
Awesome, thank you for the fix!

I don't want to ask for too much, but if you wanted to expand on this, it would be amazing to choose for each template type. So for example I would only snap to corners for squares and circles, but center and corner for lines and cones.
